compressor cleanup
SpiNNakerManchester/SpiNNFrontEndCommon pull request #642
Opened 2020-07-28 13:49 UTC by Christian-B

1. Stops run is there are no routing tables. Thanks @andrewgait 
2. Only writes iobuf is cfg write_compressor_iobuf is overwritten to true
    - mode debug will also set that to true
    - All compressors use the same cfg setting 
3. If compressor fails will extract iobuf

Must be done at same time as ...

2020-07-28 14:03 UTC, Christian-B commented
ChipPowerMonitor chance creeped in sorry, but is not wrong as Machine vertex has same functionality

2020-09-08 09:52 UTC, alan-stokes requested changes

2020-09-08 09:52 UTC, alan-stokes commented on spinn_front_end_common/interface/interface_functions/on_chip_router_table_compression/compression.py
> +        compress_as_much_as_possible=False, write_compressor_iobuf=False):
this isnt really sensible. its never called directly, and the 2 places that do call it take the write_compressor_iobuf as a required parameter. so having a default value here makes no sense.

2020-09-08 09:52 UTC, alan-stokes commented on spinn_front_end_common/interface/interface_functions/on_chip_router_table_compression/compression.py
> +        compress_as_much_as_possible=True, write_compressor_iobuf=False):
same problem here

2020-09-08 09:52 UTC, alan-stokes commented on spinn_front_end_common/interface/interface_functions/on_chip_router_table_compression/compression.py
> +        compress_as_much_as_possible=True, write_compressor_iobuf=False):
and here

2020-09-08 09:52 UTC, alan-stokes commented
apart from the default param when it cant be defaulted, i actually like this pr.

2020-09-08 11:03 UTC, alan-stokes commented on spinn_front_end_common/interface/interface_functions/on_chip_router_table_compression/compression.py
> +        compress_as_much_as_possible=True, write_compressor_iobuf=False):
fixed it for ya

2020-09-08 11:04 UTC, alan-stokes commented on spinn_front_end_common/interface/interface_functions/on_chip_router_table_compression/compression.py
> +        compress_as_much_as_possible=True, write_compressor_iobuf=False):
fixed

2020-09-10 08:16 UTC, alan-stokes commented on spinn_front_end_common/interface/interface_functions/on_chip_router_table_compression/compression.py
> +        compress_as_much_as_possible=False, write_compressor_iobuf=False):
cleaned up for ya

2020-09-10 14:08 UTC, merged