Reallocate spalloc job if known with sick board suffers
SpiNNakerManchester/SpiNNFrontEndCommon pull request #662
Opened 2020-09-17 16:12 UTC by Christian-B

Requires: https://github.com/SpiNNakerManchester/SpiNNMachine/pull/139

TODO!
Report the list of ipaddresses that are sick and not in the list.
Ideally by telling the spalloc server which delists the boards and triggers manual intervention.

2020-09-29 11:35 UTC, dkfellows commented on spinn_front_end_common/interface/interface_functions/spalloc_machine_generator.py
> +                    if sick_ip in ex.ipaddress:
This logic seems backwards. We want to exclude known bad boards from reporting, not work through the list of bad boards and check if any of them are in there. Though I suppose recovering if any of them were known is somewhat sensible too.

Need to be clear exactly what conditions trigger reporting and what trigger retrying; they might not be the same!

2020-09-29 16:31 UTC, dkfellows requested changes

2020-09-29 16:31 UTC, dkfellows commented on spinn_front_end_common/interface/interface_functions/spalloc_machine_generator.py
> +                machine_details, txrx = machine_generator(
Definitely should not call this here!

2020-09-29 16:32 UTC, dkfellows commented on spinn_front_end_common/interface/interface_functions/spalloc_machine_generator.py
> +                machine_details, txrx = machine_generator(
The problem is that this is the code that just threw, and the generator's stateless. It's got an _extremely_ high chance to throw again.

2022-01-21 14:37 UTC, Christian-B commented
So out of date and old easier to redo if ever needed.

2022-01-21 14:37 UTC, closed without merging

2023-10-05 15:18 UTC, rowleya commented
Actually happens on spalloc itself now really anyway!