Sdram partition merge
SpiNNakerManchester/SpiNNFrontEndCommon pull request #684
Opened 2020-10-27 10:38 UTC by alan-stokes

extra bits for sdram

2020-12-10 09:51 UTC, andrewgait requested changes
Looks fine to me, just a minor edit required.

2020-12-10 09:51 UTC, andrewgait commented on spinn_front_end_common/interface/interface_functions/sdram_outgoing_partition_allocator.py
> +                        "cannot allocate sdram size of 0 for "
Capital letter here.

2020-12-10 14:52 UTC, alan-stokes commented on spinn_front_end_common/interface/interface_functions/sdram_outgoing_partition_allocator.py
> +                        "cannot allocate sdram size of 0 for "
fixed i think

2020-12-15 14:33 UTC, andrewgait approved these changes

2020-12-15 16:52 UTC, merged