log warning to file
SpiNNakerManchester/SpiNNFrontEndCommon pull request #727
Opened 2020-12-15 16:39 UTC by Christian-B

cfg setting 
[Logging] warnings_at_end_to_file

if set to true will add warning and above to a warning_logs.txt file,
Regards of what level logging is set to (also in configs)

If true only print a message at end pointing to file
If false repeats warning at end of run.

Depends on: https://github.com/SpiNNakerManchester/SpiNNUtils/pull/128

2020-12-16 14:59 UTC, andrewgait requested changes
Looks good, just a minor edit

2020-12-16 14:59 UTC, andrewgait commented on spinn_front_end_common/interface/spinnaker.cfg
> +# Set to true and all log messages warning of above will be written to file
"warning or above"

2020-12-16 16:40 UTC, Christian-B commented on spinn_front_end_common/interface/spinnaker.cfg
> +# Set to true and all log messages warning of above will be written to file
fixed

2021-01-07 10:30 UTC, andrewgait approved these changes

2021-01-07 10:43 UTC, merged