Dma caching
SpiNNakerManchester/SpiNNFrontEndCommon pull request #732
Opened 2021-01-06 13:45 UTC by alan-stokes

adds bits and peices

https://github.com/SpiNNakerManchester/sPyNNaker8/pull/508

2021-01-06 14:02 UTC, rowleya approved these changes
This is fine, but the integration tests are failing...

2021-01-06 16:35 UTC, alan-stokes commented
done

2021-01-21 12:51 UTC, Christian-B requested changes
A lot of thing changed to debug.  Is this to safe space or reduce the amount of messages?

2021-01-21 12:51 UTC, Christian-B commented on c_common/front_end_common_lib/include/malloc_extras.h
> +
Not commented out. But not safe comment not removed!

2021-01-21 12:51 UTC, Christian-B commented on c_common/front_end_common_lib/src/malloc_extras.c
> +    p = safe_sdram_malloc(bytes);
Comment "try DTCM" and  call "safe_sdram"... do not match up.

2021-01-21 17:25 UTC, alan-stokes commented on c_common/front_end_common_lib/include/malloc_extras.h
> +
fixed

2021-01-21 17:26 UTC, alan-stokes commented on c_common/front_end_common_lib/src/malloc_extras.c
> +    p = safe_sdram_malloc(bytes);
fixed

2021-01-21 17:27 UTC, alan-stokes commented
purely for space. if you turn them back to info. you lose even more binaries

2023-10-03 13:06 UTC, closed without merging

2023-10-03 13:06 UTC, Christian-B commented
This is so old I don't think it is worth saving.

Please reopen if it is.

Will take major effort to bring up to date with master.